# version: "3"
# services:
#   postgres:
#     container_name: postgres-nestjs
#     image: postgres:13
#     restart: always
#     environment:
#       POSTGRES_DB: datingdb
#       POSTGRES_USER: peacover
#       POSTGRES_PASSWORD: my-password
#     # env_file:
#     #   - ./docker.env
#     ports:
#       - "5432:5432"
#     volumes:
#       - local_pgdata:/var/lib/postgresql/data
#     networks:
#       - datingapp-network

#   pgadmin:
#     depends_on:
#       - postgres
#     container_name: pgadmin-nestjs
#     image: dpage/pgadmin4
#     restart: always
#     ports:
#       - "8080:80"
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     # env_file:
#     #   - ./docker.env
#     networks:
#       - datingapp-network

# volumes:
#   local_pgdata:
#   pgadmin-data:

# networks:
#   datingapp-network:
#     driver: bridge

version: "3.8"
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=peacover
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=matcha_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
